const EVENTS = {
  movies: {
    on: {
      SEND_NEW_MOVIE_QUOTES: 'SEND_NEW_MOVIE_QUOTES',
      SEND_UPDATED_MOVIE: 'SEND_UPDATED_MOVIE',
      SEND_EDITED_QUOTE: 'SEND_EDITED_QUOTE',
      SEND_NEW_QUOTE: 'SEND_NEW_QUOTE',
      SEND_NEW_MOVIE: 'SEND_NEW_MOVIE',
      SEND_NEW_LIKE: 'SEND_NEW_LIKE',
    },

    emit: {
      DELETE_MOVIE_QUOTE: 'DELETE_MOVIE_QUOTE',
      UPDATE_MOVIE: 'UPDATE_MOVIE',
      EDIT_QUOTE: 'EDIT_QUOTE',
      LIKE_QUOTE: 'LIKE_QUOTE',
      ADD_QUOTE: 'ADD_QUOTE',
      ADD_MOVIE: 'ADD_MOVIE',
    },
  },
}

export default EVENTS
